---
title: "Merging MSPEC and PTGR data 1"
author: "Kristen Peach"
date: "4/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(ggplot2)
library(knitr)
library(dplyr)
library(readr)
library(gstat)


```
```{r load_data}

library(readr)
ForR_PTGR_TubeID <- read_csv("ForR_PTGR_TubeID.csv")

library(readr)
ForR_Petal_MSPEC <- read_csv("ForR_Petal_MSPEC.csv")


```

```{r rename_files}

PTGR <- ForR_PTGR_TubeID

Petal <- ForR_Petal_MSPEC

colnames(Petal)[colnames(Petal)=="Label"] <- "Photo_Name" #Giving the label column the same name for both files so that I can merge them



```

```{r}

Petal_PTGR <- full_join(Petal, PTGR, by = "Photo_Name")

#Merged Petal and PTGR by Photo name! Yay!



```

```{r}

library(readr)
ForR_Blade_MSPEC <- read_csv("ForR_Blade_MSPEC.csv")

Blade <- ForR_Blade_MSPEC

library(readr)
ForR_Claw_MSPEC <- read_csv("ForR_Claw_MSPEC.csv")

Claw <- ForR_Claw_MSPEC

PTGR_PCB <- full_join(Petal_PTGR, Claw, Blade, by = "Photo_Name")

PTGR_PCB2 <- PTGR_PCB %>% 
  filter(Pollen_Donor != "NA")

colnames(PTGR_PCB2)[colnames(PTGR_PCB2)=="3_6"] <- "Pollen_Type" #Giving the label column the same name for both files so that I can merge them

```


```{r}

pollen_type_anova <- aov( Comb_UVB_UVR_Mean ~ Pollen_Type, data = PTGR_PCB2)
#lobster_anova

summary(pollen_type_anova) #This gives you the p value, DF, sum sq, etc. 

pollen_type_anova2 <- aov(lumSD_UV_PETAL ~ Pollen_Type, data = PTGR_PCB2)
#lobster_anova

summary(pollen_type_anova2) 





```

